<?php

use Illuminate\Database\Seeder;

class VideosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('videos')->insert(array(
//            video_type:1->留学酷,2->crm,3->1course
//        留学酷
            0=>array(
                'video_type_id'=>'1',
                'video'=>'留学酷功能简介',
                'content'=>'1）留学酷功能简介；2）如何登陆留学酷；3）如何查看学员账号是否已开通；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTg2MjUzOTY2OA==.html?spm=a2hzp.8244740.userfeed.5!2~5~5~5!3~5~A',
                'time'=>'2:55',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            1=>array(
                'video_type_id'=>'1',
                'video'=>'创建任务',
                'content'=>'1）督导如何创建任务；2）学生如何创建任务；3）如何查看任务进度；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTg2MjUxNzg0MA==.html?spm=a2hzp.8244740.userfeed.5!4~5~5~5!3~5~A',
                'time'=>'13:45',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            2=>array(
                'video_type_id'=>'1',
                'video'=>'抽词',
                'content'=>'1）督导抽词；2）自助抽词；3）选择题抽词；4）查看抽词报告；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTg2MjUyNDgyMA==.html?spm=a2hzp.8253869.0.0&from=y1.7-2',
                'time'=>'10:20',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            3=>array(
                'video_type_id'=>'1',
                'video'=>'学生管理',
                'content'=>'1）如何添加学生；2）如何查看学生的抽查记录；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTg2MjU0MjE5Ng==.html?spm=a2hzp.8244740.userfeed.5!3~5~5~5!3~5~A',
                'time'=>'1:55',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
//            crm
            4=>array(
                'video_type_id'=>'2',
                'video'=>'CRM功能简介',
                'content'=>'1）CRM的作用及内容；2）如何登录CRM；3）账号、角色、权限等概念说明；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2NTM3OTUwNA==.html?spm=a2hzp.8244740.userfeed.5!9~5~5~5!3~5~A.UYfmbU',
                'time'=>'3:53',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            5=>array(
                'video_type_id'=>'2',
                'video'=>'CRM余额(CW)',
                'content'=>'1）什么是余额；2）如何查看学生余额；3）如何确认来款；4）余额如何退费；5）如何查看收款流水；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NDk3NDgzNg==.html',
                'time'=>'7:13',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),

            6=>array(
                'video_type_id'=>'2',
                'video'=>'CRM线索(CR)',
                'content'=>'1）线索客户管理-线索所属查询；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NDk2MDcyNA==.html',
                'time'=>'2:13',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            7=>array(
                'video_type_id'=>'2',
                'video'=>'CRM线索(FD)',
                'content'=>'1）如何查询线索所属；2）如何新增线索；3）如何确认线索上门；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NTAwODYxMg==.html',
                'time'=>'5:53',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            8=>array(
                'video_type_id'=>'2',
                'video'=>'CRM线索(CC)',
                'content'=>'1）如何查询线索所属；2）如何新增线索；3）如何管理及跟进线索；4）如何转移线索；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NTAxNTA3Ng==.html',
                'time'=>'8:40',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            9=>array(
                'video_type_id'=>'2',
                'video'=>'CRM合同(CR&CC)',
                'content'=>'1）如何创建合同（续约）；2）如何打印合同；3）如何查看合同审批进度；4）如何修改合同；5）如何撤销合同；6）如何变更合同；7）如何操作合同退费；8）如何查看合同消耗进度；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NDk2MDk4OA==.html',
                'time'=>'17:28',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            10=>array(
                'video_type_id'=>'2',
                'video'=>'CRM合同(FD)',
                'content'=>'1）如何打印合同；2）如何查看合同详情；3）如何创建教材合同；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NTAwOTk4MA==.html',
                'time'=>'9:39',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            11=>array(
                'video_type_id'=>'2',
                'video'=>'CRM合同(CW)',
                'content'=>'1）如何查看合同费用详情；2）如何确认合同收款；3）如何确认合同退费；4）如何查看合同业绩分配；5）如何查看已生产课时；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NDk3ODQ3Ng==.html',
                'time'=>'21:37',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            12=>array(
                'video_type_id'=>'2',
                'video'=>'CRM合同(DOS)',
                'content'=>'1）如何查看合同审批进度；2）如何查看合同详情及消耗进度；3）如何使用批件；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NTA0MjQxMg==.html',
                'time'=>'6:08',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            13=>array(
                'video_type_id'=>'2',
                'video'=>'CRM排课申请',
                'content'=>'1）如何发送排课申请；2）如何查看申请进度；3）如何撤销申请；4）常见操作问题及解决方案；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2MzM2MDIxMg==.html?spm=a2hzp.8244740.userfeed.5!17~5~5~5!3~5~A.UYfmbU',
                'time'=>'14:21',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            14=>array(
                'video_type_id'=>'2',
                'video'=>'CRM调课申请',
                'content'=>'1）如何发送调课申请；2）如何查看申请进度；3）如何撤销申请；4）常见操作问题及解决方案；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2MzM4Nzg2MA==.html?spm=a2hzp.8244740.userfeed.5!16~5~5~5!3~5~A.UYfmbU',
                'time'=>'8:08',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            15=>array(
                'video_type_id'=>'2',
                'video'=>'CRM测评',
                'content'=>'1）如何登记及修改考试日期；2）如何确认考试；3）如何取消考试；4）如何登记及修改考试成绩；5）如何上传考试报告及成绩截图；6）如何查看学生的考试日期和成绩；7）如何查看某场考试的学生名单及成绩；8）常见操作问题及解决方案；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2NDg1NjYxMg==.html?spm=a2hzp.8244740.userfeed.5!11~5~5~5!3~5~A.UYfmbU',
                'time'=>'30:00',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            16=>array(
                'video_type_id'=>'2',
                'video'=>'CRM班级及考团',
                'content'=>'1）如何查看班级信息；2）如何查看考团信息；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NDk3NTQwOA==.html',
                'time'=>'3:28',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            17=>array(
                'video_type_id'=>'2',
                'video'=>'CRM查看课表',
                'content'=>'1）如何查看教师课表；2）如何查看学员课表；3）如何查看小班课表；4）如何查看校区课表；5）如何查看校区教室安排；6）如何查看学员已上课时；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2MzQyMzk3Ng==.html?spm=a2hzp.8244740.userfeed.5!14~5~5~5!3~5~A.UYfmbU',
                'time'=>'6:31',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            18=>array(
                'video_type_id'=>'2',
                'video'=>'CRM培训记录',
                'content'=>'1）如何查看培训记录',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2MzQyODYwNA==.html?spm=a2hzp.8244740.userfeed.5!15~5~5~5!3~5~A.UYfmbU',
                'time'=>'2:54',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            19=>array(
                'video_type_id'=>'2',
                'video'=>'CRM回访记录',
                'content'=>'1）如何填写回访记录；2）如何查看已填写的回访记录；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2MzQzNzU3Mg==.html?spm=a2hzp.8244740.userfeed.5!13~5~5~5!3~5~A.UYfmbU',
                'time'=>'3:07',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            20=>array(
                'video_type_id'=>'2',
                'video'=>'CRM其他操作介绍(TA)',
                'content'=>'1）如何查看及解读学员档案；2）如何查看学员的合同详情；3）如何查看小班学员；4）如何查看学员的到校签到情况；5）如何查看学员的教学事故记录；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2NDk2OTM4NA==.html?spm=a2hzp.8244740.userfeed.5!10~5~5~5!3~5~A.UYfmbU',
                'time'=>'11:39',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            21=>array(
                'video_type_id'=>'2',
                'video'=>'CRM学员',
                'content'=>'1）如何查看学员的签到记录；2）如何查看学员的培训记录；3）如何查看学员的回访记录；4）如何查看学员的课表；5）如何查看学员的教学事故；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NDk2MTQ2OA==.html',
                'time'=>'5:13',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            22=>array(
                'video_type_id'=>'2',
                'video'=>'CRM来款',
                'content'=>'1）如何登记来款；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NTAwNjQzNg==.html',
                'time'=>'3:53',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            23=>array(
                'video_type_id'=>'2',
                'video'=>'CRM教材',
                'content'=>'1）如何查看校区教材库存；2）如何申请增加教材；3）如何把教材入库；4）如何操作学生领书；5）如何操作退书；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NTAwODg4NA==.html',
                'time'=>'10:02',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            24=>array(
                'video_type_id'=>'2',
                'video'=>'CRM课程',
                'content'=>'1）如何查看校区课表；2）如何查看上课签到情况；3）如何查看教师课表；4）如何查看学员课表；5）如何查看小班信息；',
                'saved_at'=>'',
                'time'=>'2:51',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            25=>array(
                'video_type_id'=>'2',
                'video'=>'CRM教室',
                'content'=>'1）如何安排上课教室；2）如何新增教室；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NTAwNTcyNA==.html',
                'time'=>'2:16',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            26=>array(
                'video_type_id'=>'2',
                'video'=>'CRM平板',
                'content'=>'1）如何新增平板；2）如何将平板出库；3）如何将平板入库；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NTAwNTI2NA==.html',
                'time'=>'2:26',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            27=>array(
                'video_type_id'=>'2',
                'video'=>'CRM课表课量',
                'content'=>'1）如何查看教师课表；2）如何查看学员课表；3）如何查看小班课表；4）如何查看教师的授课科目；5）如何查看教师的可排课量；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NDk3NTEyMA==.html',
                'time'=>'6:27',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            28=>array(
                'video_type_id'=>'2',
                'video'=>'CRM测评(CC)',
                'content'=>'1）如何登记历史成绩；2）如何登记及修改考试日期；3）如何确认考试；4）如何取消考试；5）如何登记及修改考试成绩；6）如何上传考试报告及成绩截图；7）如何查看学生的考试日期和成绩；8）如何查看某场考试的学生名单及成绩；9）常见操作问题及解决方案；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NDk4MTgzNg==.html',
                'time'=>'35:20',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            29=>array(
                'video_type_id'=>'2',
                'video'=>'CRM学员(DOS)',
                'content'=>'1）如何添加及变更学员督导；2）如何变更学员的培训状态；3）如何解读学员档案；4）如何查看回访记录；5）如何查看签到记录；6）如何查看培训记录；7）如何查看学员课表；8）如何开通抽词账号；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NTA0Njc0OA==.html',
                'time'=>'18:36',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            30=>array(
                'video_type_id'=>'2',
                'video'=>'CRM教学事故',
                'content'=>'1）如何确认教学事故；2）如何查看事故制度的执行情况；3）如何统计教学事故；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NjM5OTAwOA==.html',
                'time'=>'3:48',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            31=>array(
                'video_type_id'=>'2',
                'video'=>'CRM校区',
                'content'=>'1）如何查看校区教材库存；2）如何申请增加教材库存；3）如何操作平板借用；4）如何查看校区课表；5）如何查看教室安排；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NTA0MjcyNA==.html',
                'time'=>'5:54',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            32=>array(
                'video_type_id'=>'2',
                'video'=>'CRM排课',
                'content'=>'1）如何查看排课申请；2）一对一排课（合同付费情况）；3）如何查看排课记录；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NjExNTYwOA==.html',
                'time'=>'16:03',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            33=>array(
                'video_type_id'=>'2',
                'video'=>'CRM调课',
                'content'=>'1）如何查看调课申请；2）一对一调课；3）如何查看调课记录；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NjIxNDM5Ng==.html',
                'time'=>'8:51',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            34=>array(
                'video_type_id'=>'2',
                'video'=>'CRM小班管理',
                'content'=>'1）如何设班；2）小班排课；3）小班调课；4）取消班级；5）如何查看报班情况；6）转班确认；7）退班确认；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NjI2NjY2MA==.html',
                'time'=>'10:47',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            35=>array(
                'video_type_id'=>'2',
                'video'=>'CRM教师课量管理',
                'content'=>'1）教师如何查看课表；2）如何设置教师授课信息；3）如何确认课时；4）如何查看及统计教师课量；5）教师休假管理；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NjMyMjQ2OA==.html',
                'time'=>'13:14',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            36=>array(
                'video_type_id'=>'2',
                'video'=>'CRM培训记录(JW)',
                'content'=>'1）教师如何填写培训记录；2）如何查看培训记录；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NjMzNzEyOA==.html',
                'time'=>'2:56',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            37=>array(
                'video_type_id'=>'2',
                'video'=>'CRM教学事故(JW)',
                'content'=>'1）教师如何签到；2）如何确认教学事故；3）如何执行教学事故奖惩方案；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NjM3NTg1Mg==.html',
                'time'=>'8:06',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            38=>array(
                'video_type_id'=>'2',
                'video'=>'CRM查看学员信息',
                'content'=>'1）如何查看学员所属信息；2）如何查看学员课表；3）如何查看校区课表；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjQ5NjM4Njc1Ng==.html',
                'time'=>'1:59',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
//            1course
            39=>array(
                'video_type_id'=>'3',
                'video'=>'1course功能简介',
                'content'=>'1）1course功能简介；2）如何登陆1course；3）老师界面功能介绍；4）如何查看学生账号是否开通；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjMzMjc0MDQ5Mg==.html?spm=a2hzp.8253869.0.0&from=y1.7-2',
                'time'=>'3:07',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            40=>array(
                'video_type_id'=>'3',
                'video'=>'入学测试',
                'content'=>'1）如何创建入学测试；2）学生如何进行测试；3）如何查看测试进度；4）如何查看测试报告；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjMzMjM4OTYxMg==.html?spm=a2hzp.8253869.0.0&from=y1.7-2',
                'time'=>'7:08',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            41=>array(
                'video_type_id'=>'3',
                'video'=>'阶段测试',
                'content'=>'1）如何创建阶段测试；2）学生如何进行测试；3）如何查看测试进度；4）如何查看测试报告；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMjMzMjg5MTEwOA==.html?from=y1.7-2&spm=a2hzp.8253869.0.0',
                'time'=>'11:17',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            42=>array(
                'video_type_id'=>'3',
                'video'=>'智能口语测评',
                'content'=>'1）如何创建口语测评；2）学生如何进行测评；3）如何查看测评报告；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc0NDk1NTU4NA==.html?spm=a2hzp.8253869.0.0&from=y1.7-2',
                'time'=>'5:45',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
        ));
    }
}
