<?php

use Illuminate\Database\Seeder;

class VideosTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('videos')->insert(array(
//            video_type:1->留学酷,2->crm,3->1course
//        留学酷
            0=>array(
                'video_type_id'=>'1',
                'video'=>'留学酷功能简介',
                'content'=>'1）留学酷功能简介；2）如何登陆留学酷；3）如何查看学员账号是否已开通；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTg2MjUzOTY2OA==.html?spm=a2hzp.8244740.userfeed.5!2~5~5~5!3~5~A',
                'time'=>'2:55',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            1=>array(
                'video_type_id'=>'1',
                'video'=>'创建任务',
                'content'=>'1）督导如何创建任务；2）学生如何创建任务；3）如何查看任务进度；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTg2MjUxNzg0MA==.html?spm=a2hzp.8244740.userfeed.5!4~5~5~5!3~5~A',
                'time'=>'13:45',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            2=>array(
                'video_type_id'=>'1',
                'video'=>'抽词',
                'content'=>'1）督导抽词；2）自助抽词；3）选择题抽词；4）查看抽词报告；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTg2MjUyNDgyMA==.html?spm=a2hzp.8253869.0.0&from=y1.7-2',
                'time'=>'10:20',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            3=>array(
                'video_type_id'=>'1',
                'video'=>'学生管理',
                'content'=>'1）如何添加学生；2）如何查看学生的抽查记录；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTg2MjU0MjE5Ng==.html?spm=a2hzp.8244740.userfeed.5!3~5~5~5!3~5~A',
                'time'=>'1:55',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
//            crm
            4=>array(
                'video_type_id'=>'2',
                'video'=>'CRM功能简介',
                'content'=>'1）CRM的作用及内容；2）如何登录CRM；3）账号、角色、权限等概念说明；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2NTM3OTUwNA==.html?spm=a2hzp.8244740.userfeed.5!9~5~5~5!3~5~A.UYfmbU',
                'time'=>'3:53',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            5=>array(
                'video_type_id'=>'2',
                'video'=>'CRM排课申请',
                'content'=>'1）如何发送排课申请；2）如何查看申请进度；3）如何撤销申请；4）常见操作问题及解决方案；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2MzM2MDIxMg==.html?spm=a2hzp.8244740.userfeed.5!17~5~5~5!3~5~A.UYfmbU',
                'time'=>'14:21',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            6=>array(
                'video_type_id'=>'2',
                'video'=>'CRM调课申请',
                'content'=>'1）如何发送调课申请；2）如何查看申请进度；3）如何撤销申请；4）常见操作问题及解决方案；',
                'saved_at'=>'http://v.youku.com/v_show/id_XMTc2MzM4Nzg2MA==.html?spm=a2hzp.8244740.userfeed.5!16~5~5~5!3~5~A.UYfmbU',
                'time'=>'8:08',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            7=>array(
                'video_type_id'=>'2',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            8=>array(
                'video_type_id'=>'2',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            9=>array(
                'video_type_id'=>'2',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            10=>array(
                'video_type_id'=>'2',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            11=>array(
                'video_type_id'=>'2',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            12=>array(
                'video_type_id'=>'2',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            13=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            14=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            15=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            16=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            17=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            18=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            19=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            20=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            21=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            22=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            23=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            24=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            25=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            26=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            27=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            28=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            29=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            30=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            31=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
            32=>array(
                'video_type_id'=>'',
                'video'=>'',
                'content'=>'',
                'saved_at'=>'',
                'time'=>'',
                'teacher'=>'刘丹霞',
                'status'=>'使用中',
                'created_at'=>date('Y-m-d H:i:s'),
                'updated_at'=>date('Y-m-d H:i:s'),
            ),
        ));
    }
}
